spring:
  application:
    name: accounts-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/accounts-server/templates/
error:
  path: /error
server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 5