server:
  port: 4444
spring:
  application:
    name: customers-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/customers-server/templates/
  error:
    path: /error
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/classicmodels
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: null
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 5